# Generated by Django 5.2.7 on 2025-11-03 23:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField()),
                ('image', models.ImageField(upload_to='shirts')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failed')])),
            ],
        ),
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mockups')),
                ('font', models.CharField(blank=True, default='FiraCode-Bold', max_length=255)),
                ('text_color', models.CharField(blank=True, default='FFFFFF', max_length=6)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('shirt_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='api.shirt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='api.task')),
            ],
        ),
    ]
