# Generated by Django 5.2.7 on 2025-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_mockup_shirt_color_delete_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='font',
            field=models.CharField(blank=True, choices=[('FiraCode', 'Firacode'), ('ArialCEItalic', 'Arialceitalic'), ('ArialMdm', 'Arialmdm'), ('ArialMdmItl', 'Arialmdmitl'), ('arialceb', 'Arialceb'), ('ArialCE', 'Arialce'), ('ArialCEMTBlack', 'Arialcemtblack'), ('ArialCEBoldItalic', 'Arialcebolditalic'), ('Arial', 'Arial')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='shirt_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='text_color',
            field=models.CharField(blank=True, choices=[('0000FF', 'Blue'), ('FFFFFF', 'White'), ('FFFF00', 'Yellow'), ('000000', 'Black')], default='FFFFFF', max_length=6),
        ),
    ]
