# Generated by Django 5.2.7 on 2025-11-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mockup_owner_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockup',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
    ]
