# Generated by Django 5.2.7 on 2025-11-04 10:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_mockup_owner_remove_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.create_path),
        ),
    ]
